[[input.prepend_keymap]]
on   = [ "<Esc>" ]
exec = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on   = [ "l" ]
exec = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
exec = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"
